server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mohirdev
    username: mohirdev
    password: gghhjjkkll
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update